# Generated by Django 5.0.6 on 2024-08-25 12:13

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_post', models.CharField(choices=[('tank', 'Танк'), ('hill', 'Хил'), ('dd', 'ДД'), ('dealer', 'Торговец'), ('guildmaster', 'Гилдмастер'), ('questgiver', 'Квестгивер'), ('blacksmith', 'Кузнец'), ('tanner', 'Кожевник'), ('potion_master', 'Зельевар'), ('spell_master', 'Мастер Заклинаний')], default='tank', max_length=13)),
                ('title', models.CharField(max_length=200)),
                ('content', tinymce.models.HTMLField()),
                ('status', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('Accepted', 'Принято'), ('Rejected', 'Отклонено'), ('Not defined', 'Не определено')], default='Not defined', max_length=11)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcement.post')),
            ],
        ),
    ]
